# Generated by Django 3.1.1 on 2020-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hot_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
